blank_issues_enabled: true
contact_links:
  - name: EverythingPT is a Virus
    url: https://github.com/lin-ycv/EverythingPowerToys/wiki/Known-Issues#flagged-by-antivirus-as-malicious
    about: Installer being quarantined/Antivirus removes the installer.
  - name: How do I use/configure...
    url: https://github.com/lin-ycv/EverythingPowerToys/wiki/Features
    about: EverythingPT is working, but not the way you want.
  - name: Review open issues
    url: https://github.com/lin-ycv/EverythingPowerToys/issues?q=is%3Aissue
    about: Please check if your issue isn't already there.